export const TOGGLE_CART_PREVIEW = 'TOGGLE_CART_PREVIEW';
export const ADD_ITEM = 'ADD_ITEM';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';